common:
  app:
    url: "%env(APP_URL)%"
    name: "%env(APP_NAME)%"
    version: "%version%"
    logo: "%env(APP_LOGO)%"
  locales: "%locales%"
  menu: mainMenu
  templates:
    mail: '_mail/index.html.twig'
    logs: '_logs/index.html.twig'
    clear_logs: '_logs/clear.html.twig'