kivuto:
  account: "%env(KIVUTO_ACCOUNT)%"
  endpoint: "%env(KIVUTO_ENDPOINT)%"
  secret_key: "%env(KIVUTO_SECRET_KEY)%"
  guzzle: eight_points_guzzle.client.kivuto
  logger: logger
  data_resolver: App\Kivuto\DataResolver
  fake:
    enabled: false