kivuto:
  endpoint: "%env(KIVUTO_ENDPOINT)%"
  secret_key: "%env(KIVUTO_SECRET_KEY)%"
  guzzle: guzzle.client.kivuto
  logger: logger
  data_resolver: App\Kivuto\DataResolver
  fake:
    enabled: true