# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database:
            entity:
                class: App:User
                property: username

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_STUDENT: ROLE_USER
        ROLE_ADMIN: ROLE_USER

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            anonymous: ~
            pattern: ^/saml/(login|discovery)$

        secured:
            pattern: ^/
            light_saml_sp:
                provider: database       # user provider name configured in step 9
                user_creator: saml.user_creator  # name of the user creator service created in step 10
                login_path: /saml/login
                check_path: /saml/login_check
                attribute_mapper: saml.attribute_mapper
            logout:
                path: /logout

        main:
            anonymous: ~